# Generated by Django 4.0.2 on 2022-02-27 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_post_likes_alter_photo_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
