# Generated by Django 4.0.2 on 2022-03-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ManyToManyField(related_name='posts', to='myproject.Post'),
        ),
    ]
