# Generated by Django 4.0.2 on 2022-03-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_remove_photo_post_photo_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ManyToManyField(to='myproject.Photo'),
        ),
    ]
