# Generated by Django 4.0.2 on 2022-03-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
