# Generated by Django 4.0.2 on 2022-03-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='logo',
        ),
    ]
