# Generated by Django 4.0.2 on 2022-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_price_product_price_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_month',
            field=models.CharField(blank=True, choices=[('', ''), ('month', 'month')], default=False, max_length=25),
        ),
    ]
