# Generated by Django 4.0.2 on 2022-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_price_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
