# Generated by Django 4.0.2 on 2022-03-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='post/single-post/')),
                ('product', models.ManyToManyField(related_name='posts', to='app.Product')),
            ],
        ),
    ]
