# Generated by Django 4.0.2 on 2022-03-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_imagepost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='slug',
        ),
    ]
