# Generated by Django 4.0.2 on 2022-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_imagepost_product_imagepost_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='product',
            field=models.ManyToManyField(related_name='posts', to='app.Product'),
        ),
    ]
