# Generated by Django 4.0.2 on 2022-03-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_imagepost_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='product',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.product'),
        ),
    ]
