# Generated by Django 4.0.2 on 2022-03-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_company_worker_company_worker_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, upload_to='worker/'),
        ),
    ]
