# Generated by Django 4.0.2 on 2022-03-05 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_worker_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='worker_user',
        ),
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
