# Generated by Django 4.0.2 on 2022-03-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_worker_user_worker_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_company',
            field=models.ImageField(blank=True, upload_to='logo_company/'),
        ),
    ]
