# Generated by Django 4.0.2 on 2022-03-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='slug',
            field=models.SlugField(),
        ),
    ]
